### ISSUE TITLE
Creating the sign-up page

### ISSUE THREAD

**Issue by McNaBry** [McNaBry/orbital-grindtogether#3]
Creating the sign-up page which can direct the user to:
1. The sign-in page if he/she already has an account
2. The default starting page for the web application

(Just a basic mock-up without actual authentication function yet)

**Comment by tjch-o** [comment]
Future features to KIV and implement:
1.  Email verification to ensure no repeats 
2.  Send the inputs after password and email verification checks are passed to a database
